import json
import tomllib
from pathlib import Path
from typing import Any

SYNTAX_DIR: Path = Path(__file__).parent
SYNTAXES = ['django', 'django-html', 'django-txt']


def load(path: Path) -> dict[str, Any]:
    with path.open('rb') as f:
        return tomllib.loads(f.read().decode('utf-8'))


def build_file(syntax: str) -> None:
    data: dict[str, Any] = load(SYNTAX_DIR / f'{syntax}.toml')
    data['_comment'] = 'Generated by build script'

    if 'repositories' in data:
        for name in data['repositories']:
            repo: dict[str, Any] = load(SYNTAX_DIR / 'repositories' / f'{name}.toml')
            data['repository'][name] = repo

        data.pop('repositories', None)

    output_path = Path('syntaxes') / f'{syntax}.tmLanguage.json'
    with output_path.open('w') as f:
        json.dump(data, f, indent=2)


def main() -> None:
    for syntax in SYNTAXES:
        build_file(syntax)


if __name__ == '__main__':
    main()
